apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies
  namespace: opa-keycloak-practice
data:
  policy.rego: |
    package system.authz
    
    default allow := false
    
    allow if {
        valid_token
        has_permission
    }
    
    valid_token if {
        input.token
        count(io.jwt.decode(input.token)) == 3
    }
    
    user := payload if {
        [_, payload, _] := io.jwt.decode(input.token)
    }
    
    has_permission if {
        "manager" in user.realm_access.roles
    }
    
    has_permission if {
        "hr-staff" in user.realm_access.roles
        not input.method == "DELETE"
    }
    
    has_permission if {
        "employee" in user.realm_access.roles
        input.method == "GET"
        path_parts := split(input.path, "/")
        count(path_parts) >= 3
        employee_path_id := path_parts[2]
        user.employee_id == employee_path_id
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa-keycloak-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest-envoy
        ports:
        - containerPort: 8181
        - containerPort: 9191
        args:
          - "run"
          - "--server"
          - "--addr=0.0.0.0:8181"
          - "/policies/policy.rego"
        volumeMounts:
        - name: opa-policies
          mountPath: /policies
        env:
        - name: OPA_LOG_LEVEL
          value: "debug"
      volumes:
      - name: opa-policies
        configMap:
          name: opa-policies
---
apiVersion: v1
kind: Service
metadata:
  name: opa-service
  namespace: opa-keycloak-practice
spec:
  selector:
    app: opa
  ports:
  - name: http
    port: 8181
    targetPort: 8181
  - name: grpc
    port: 9191
    targetPort: 9191