apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opa-demo-kong
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: opa-demo.local
    http:
      paths:
      # Route everything through Kong Gateway
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-gateway-service
            port:
              number: 8000 