spring.application.name=merchant-service
server.port=8080

# Logging configuration
logging.level.com.anmolsekhon.merchant_service=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Management endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
